/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasoRouteImport } from './routes/caso'
import { Route as DossieRouteImport } from './routes/dossie'
import { Route as JogarRouteImport } from './routes/jogar'
import { Route as PlantaoRouteImport } from './routes/plantao'
import { Route as ProtocoloRouteImport } from './routes/protocolo'
import { Route as BriefingIndexRouteImport } from './routes/briefing.index'
import { Route as BriefingIdRouteImport } from './routes/briefing.$id'
import { Route as DesafiosIndexRouteImport } from './routes/desafios.index'
import { Route as DesafiosIdRouteImport } from './routes/desafios.$id'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as LabIdRouteImport } from './routes/lab.$id'
import { Route as QrIndexRouteImport } from './routes/qr.index'
import { Route as QrIdRouteImport } from './routes/qr.$id'
import { Route as VozIndexRouteImport } from './routes/voz.index'
import { Route as VozIdRouteImport } from './routes/voz.$id'
import { Route as XIndexRouteImport } from './routes/x.index'
import { Route as XIdRouteImport } from './routes/x.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasoRoute = CasoRouteImport.update({
  id: '/caso',
  path: '/caso',
  getParentRoute: () => rootRouteImport,
} as any)
const DossieRoute = DossieRouteImport.update({
  id: '/dossie',
  path: '/dossie',
  getParentRoute: () => rootRouteImport,
} as any)
const JogarRoute = JogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantaoRoute = PlantaoRouteImport.update({
  id: '/plantao',
  path: '/plantao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocoloRoute = ProtocoloRouteImport.update({
  id: '/protocolo',
  path: '/protocolo',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingIndexRoute = BriefingIndexRouteImport.update({
  id: '/briefing/',
  path: '/briefing/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingIdRoute = BriefingIdRouteImport.update({
  id: '/briefing/$id',
  path: '/briefing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosIndexRoute = DesafiosIndexRouteImport.update({
  id: '/desafios/',
  path: '/desafios/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosIdRoute = DesafiosIdRouteImport.update({
  id: '/desafios/$id',
  path: '/desafios/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIdRoute = LabIdRouteImport.update({
  id: '/lab/$id',
  path: '/lab/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QrIndexRoute = QrIndexRouteImport.update({
  id: '/qr/',
  path: '/qr/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrIdRoute = QrIdRouteImport.update({
  id: '/qr/$id',
  path: '/qr/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VozIndexRoute = VozIndexRouteImport.update({
  id: '/voz/',
  path: '/voz/',
  getParentRoute: () => rootRouteImport,
} as any)
const VozIdRoute = VozIdRouteImport.update({
  id: '/voz/$id',
  path: '/voz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const XIndexRoute = XIndexRouteImport.update({
  id: '/x/',
  path: '/x/',
  getParentRoute: () => rootRouteImport,
} as any)
const XIdRoute = XIdRouteImport.update({
  id: '/x/$id',
  path: '/x/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caso': typeof CasoRoute
  '/dossie': typeof DossieRoute
  '/jogar': typeof JogarRoute
  '/plantao': typeof PlantaoRoute
  '/protocolo': typeof ProtocoloRoute
  '/briefing/$id': typeof BriefingIdRoute
  '/desafios/$id': typeof DesafiosIdRoute
  '/lab/$id': typeof LabIdRoute
  '/qr/$id': typeof QrIdRoute
  '/voz/$id': typeof VozIdRoute
  '/x/$id': typeof XIdRoute
  '/briefing/': typeof BriefingIndexRoute
  '/desafios/': typeof DesafiosIndexRoute
  '/lab/': typeof LabIndexRoute
  '/qr/': typeof QrIndexRoute
  '/voz/': typeof VozIndexRoute
  '/x/': typeof XIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caso': typeof CasoRoute
  '/dossie': typeof DossieRoute
  '/jogar': typeof JogarRoute
  '/plantao': typeof PlantaoRoute
  '/protocolo': typeof ProtocoloRoute
  '/briefing/$id': typeof BriefingIdRoute
  '/desafios/$id': typeof DesafiosIdRoute
  '/lab/$id': typeof LabIdRoute
  '/qr/$id': typeof QrIdRoute
  '/voz/$id': typeof VozIdRoute
  '/x/$id': typeof XIdRoute
  '/briefing': typeof BriefingIndexRoute
  '/desafios': typeof DesafiosIndexRoute
  '/lab': typeof LabIndexRoute
  '/qr': typeof QrIndexRoute
  '/voz': typeof VozIndexRoute
  '/x': typeof XIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caso': typeof CasoRoute
  '/dossie': typeof DossieRoute
  '/jogar': typeof JogarRoute
  '/plantao': typeof PlantaoRoute
  '/protocolo': typeof ProtocoloRoute
  '/briefing/$id': typeof BriefingIdRoute
  '/desafios/$id': typeof DesafiosIdRoute
  '/lab/$id': typeof LabIdRoute
  '/qr/$id': typeof QrIdRoute
  '/voz/$id': typeof VozIdRoute
  '/x/$id': typeof XIdRoute
  '/briefing/': typeof BriefingIndexRoute
  '/desafios/': typeof DesafiosIndexRoute
  '/lab/': typeof LabIndexRoute
  '/qr/': typeof QrIndexRoute
  '/voz/': typeof VozIndexRoute
  '/x/': typeof XIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caso'
    | '/dossie'
    | '/jogar'
    | '/plantao'
    | '/protocolo'
    | '/briefing/$id'
    | '/desafios/$id'
    | '/lab/$id'
    | '/qr/$id'
    | '/voz/$id'
    | '/x/$id'
    | '/briefing/'
    | '/desafios/'
    | '/lab/'
    | '/qr/'
    | '/voz/'
    | '/x/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caso'
    | '/dossie'
    | '/jogar'
    | '/plantao'
    | '/protocolo'
    | '/briefing/$id'
    | '/desafios/$id'
    | '/lab/$id'
    | '/qr/$id'
    | '/voz/$id'
    | '/x/$id'
    | '/briefing'
    | '/desafios'
    | '/lab'
    | '/qr'
    | '/voz'
    | '/x'
  id:
    | '__root__'
    | '/'
    | '/caso'
    | '/dossie'
    | '/jogar'
    | '/plantao'
    | '/protocolo'
    | '/briefing/$id'
    | '/desafios/$id'
    | '/lab/$id'
    | '/qr/$id'
    | '/voz/$id'
    | '/x/$id'
    | '/briefing/'
    | '/desafios/'
    | '/lab/'
    | '/qr/'
    | '/voz/'
    | '/x/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasoRoute: typeof CasoRoute
  DossieRoute: typeof DossieRoute
  JogarRoute: typeof JogarRoute
  PlantaoRoute: typeof PlantaoRoute
  ProtocoloRoute: typeof ProtocoloRoute
  BriefingIdRoute: typeof BriefingIdRoute
  DesafiosIdRoute: typeof DesafiosIdRoute
  LabIdRoute: typeof LabIdRoute
  QrIdRoute: typeof QrIdRoute
  VozIdRoute: typeof VozIdRoute
  XIdRoute: typeof XIdRoute
  BriefingIndexRoute: typeof BriefingIndexRoute
  DesafiosIndexRoute: typeof DesafiosIndexRoute
  LabIndexRoute: typeof LabIndexRoute
  QrIndexRoute: typeof QrIndexRoute
  VozIndexRoute: typeof VozIndexRoute
  XIndexRoute: typeof XIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caso': {
      id: '/caso'
      path: '/caso'
      fullPath: '/caso'
      preLoaderRoute: typeof CasoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossie': {
      id: '/dossie'
      path: '/dossie'
      fullPath: '/dossie'
      preLoaderRoute: typeof DossieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogar': {
      id: '/jogar'
      path: '/jogar'
      fullPath: '/jogar'
      preLoaderRoute: typeof JogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantao': {
      id: '/plantao'
      path: '/plantao'
      fullPath: '/plantao'
      preLoaderRoute: typeof PlantaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolo': {
      id: '/protocolo'
      path: '/protocolo'
      fullPath: '/protocolo'
      preLoaderRoute: typeof ProtocoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing/': {
      id: '/briefing/'
      path: '/briefing'
      fullPath: '/briefing/'
      preLoaderRoute: typeof BriefingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing/$id': {
      id: '/briefing/$id'
      path: '/briefing/$id'
      fullPath: '/briefing/$id'
      preLoaderRoute: typeof BriefingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios/': {
      id: '/desafios/'
      path: '/desafios'
      fullPath: '/desafios/'
      preLoaderRoute: typeof DesafiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios/$id': {
      id: '/desafios/$id'
      path: '/desafios/$id'
      fullPath: '/desafios/$id'
      preLoaderRoute: typeof DesafiosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$id': {
      id: '/lab/$id'
      path: '/lab/$id'
      fullPath: '/lab/$id'
      preLoaderRoute: typeof LabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/': {
      id: '/qr/'
      path: '/qr'
      fullPath: '/qr/'
      preLoaderRoute: typeof QrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$id': {
      id: '/qr/$id'
      path: '/qr/$id'
      fullPath: '/qr/$id'
      preLoaderRoute: typeof QrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voz/': {
      id: '/voz/'
      path: '/voz'
      fullPath: '/voz/'
      preLoaderRoute: typeof VozIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voz/$id': {
      id: '/voz/$id'
      path: '/voz/$id'
      fullPath: '/voz/$id'
      preLoaderRoute: typeof VozIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x/': {
      id: '/x/'
      path: '/x'
      fullPath: '/x/'
      preLoaderRoute: typeof XIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x/$id': {
      id: '/x/$id'
      path: '/x/$id'
      fullPath: '/x/$id'
      preLoaderRoute: typeof XIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasoRoute: CasoRoute,
  DossieRoute: DossieRoute,
  JogarRoute: JogarRoute,
  PlantaoRoute: PlantaoRoute,
  ProtocoloRoute: ProtocoloRoute,
  BriefingIdRoute: BriefingIdRoute,
  DesafiosIdRoute: DesafiosIdRoute,
  LabIdRoute: LabIdRoute,
  QrIdRoute: QrIdRoute,
  VozIdRoute: VozIdRoute,
  XIdRoute: XIdRoute,
  BriefingIndexRoute: BriefingIndexRoute,
  DesafiosIndexRoute: DesafiosIndexRoute,
  LabIndexRoute: LabIndexRoute,
  QrIndexRoute: QrIndexRoute,
  VozIndexRoute: VozIndexRoute,
  XIndexRoute: XIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
